# Builds and runs tests

name: Build Binaries

# Controls when the workflow will run
on:
  push:
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          
      # Run luajit build script
      - name: CI Build
        run: cargo build --release

      - name: Zip Archive (linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir lib
          cp target/release/libtrussfs.so lib/
          zip -r "trussfs_${{ matrix.os }}.zip" lib include LICENSE README.md
          
      - name: Zip Archive (windows)
        if: matrix.os == 'windows-latest'
        run: |
          mkdir lib
          cp target/release/trussfs.dll lib/
          cp target/release/trussfs.dll.lib lib/
          7z a "trussfs_${{ matrix.os }}.zip" lib include LICENSE README.md
          
      - name: Publish Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: trussfs_${{ matrix.os }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}
